// This file was generated by silverstripe/tx-translator from client/lang/src/en.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('en', {
    "SessionManager.ACTIVITY_TOOLTIP_TEXT": "Signed in {signedIn}, Last active {lastActive}",
    "SessionManager.AUTHENTICATED": "authenticated {createdElapsed}...",
    "SessionManager.CONFIRMATION_TITLE": "Are you sure?",
    "SessionManager.COULD_NOT_LOGOUT": "Could not log out of session. Try again later.",
    "SessionManager.CURRENT": "Current",
    "SessionManager.DELETE_CONFIRMATION_BUTTON": "Remove login session",
    "SessionManager.LAST_ACTIVE": "last active {lastAccessedElapsed}...",
    "SessionManager.LOGGING_OUT": "Logging out...",
    "SessionManager.LOG_OUT": "Log out"
});
}