// This file was generated by silverstripe/cow from client/lang/src/nl.json.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('nl', {
    "SessionManager.CONFIRMATION_TITLE": "Weet je het zeker?",
    "SessionManager.DELETE_CONFIRMATION_BUTTON": "Verwijder ingelogde sessie",
    "SessionManager.CURRENT": "Huidige",
    "SessionManager.AUTHENTICATED": "ingelogd {createdElapsed}...",
    "SessionManager.LAST_ACTIVE": "laatst actief {lastAccessedElapsed}...",
    "SessionManager.LOG_OUT": "Uitloggen",
    "SessionManager.LOGGING_OUT": "Uitloggen...",
    "SessionManager.ACTIVITY_TOOLTIP_TEXT": "Ingelogd {signedIn}, laatst actief {lastActive}",
    "SessionManager.COULD_NOT_LOGOUT": "Could not log out of session. Try again later."
});
}