// This file was generated by silverstripe/tx-translator from client/lang/src/sk.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sk', {
    "SessionManager.ACTIVITY_TOOLTIP_TEXT": "Prihlásený {signedIn}, naposledy aktívny {lastActive}",
    "SessionManager.AUTHENTICATED": "overený {createdElapsed}...",
    "SessionManager.CONFIRMATION_TITLE": "Ste si istý?",
    "SessionManager.COULD_NOT_LOGOUT": "Nepodarilo sa odhlásiť z relácie. Skúste to znovu neskôr.",
    "SessionManager.CURRENT": "Aktuálny",
    "SessionManager.DELETE_CONFIRMATION_BUTTON": "Odstrániť reláciu prihlásenia",
    "SessionManager.LAST_ACTIVE": "naposledy aktívny {lastAccessedElapsed}...",
    "SessionManager.LOGGING_OUT": "Odhlasuje sa...",
    "SessionManager.LOG_OUT": "Odhlásiť sa"
});
}