// This file was generated by silverstripe/tx-translator from client/lang/src/sl.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sl', {
    "SessionManager.ACTIVITY_TOOLTIP_TEXT": "Prijavljen {signedIn}, Nazadnje aktiven {lastActive}",
    "SessionManager.AUTHENTICATED": "avtenticiran {createdElapsed}...",
    "SessionManager.CONFIRMATION_TITLE": "Potrdite akcijo",
    "SessionManager.COULD_NOT_LOGOUT": "Ni vas bilo mogoče odjaviti. Poskusite ponovno kasneje.",
    "SessionManager.CURRENT": "Trenutno",
    "SessionManager.DELETE_CONFIRMATION_BUTTON": "Izvedi odjave",
    "SessionManager.LAST_ACTIVE": "nazadnje aktiven {lastAccessedElapsed}...",
    "SessionManager.LOGGING_OUT": "Odjavljam ...",
    "SessionManager.LOG_OUT": "Odjava"
});
}