// This file was generated by silverstripe/tx-translator from client/lang/src/tr_TR.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('tr_TR', {
    "SessionManager.CONFIRMATION_TITLE": "Emin misin sen?",
    "SessionManager.DELETE_CONFIRMATION_BUTTON": "Oturum açmaya girişi kaldır",
    "SessionManager.CURRENT": "Geçerli",
    "SessionManager.AUTHENTICATED": "authenticated {createdElapsed}...",
    "SessionManager.LAST_ACTIVE": "last active {lastAccessedElapsed}...",
    "SessionManager.LOG_OUT": "Çıkış yap",
    "SessionManager.LOGGING_OUT": "Oturum kapatılıyor...",
    "SessionManager.ACTIVITY_TOOLTIP_TEXT": "Signed in {signedIn}, Last active {lastActive}",
    "SessionManager.COULD_NOT_LOGOUT": "Oturumdan çıkış yapılamadı. Daha sonra tekrar deneyin."
});
}