---
Name: session-manager
---
SilverStripe\Security\Member:
  extensions:
    - 'SilverStripe\SessionManager\Extensions\MemberExtension'
SilverStripe\Security\RememberLoginHash:
  extensions:
    - 'SilverStripe\SessionManager\Extensions\RememberLoginHashExtension'
---
Name: session-manager-log-in-handler
After: '#coreauthentication'
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\SessionManager\Security\LogInAuthenticationHandler:
    properties:
      SessionVariable: activeLoginSession
  SilverStripe\Security\AuthenticationHandler:
    properties:
      Handlers:
        LoginSessionLogIn: '%$SilverStripe\SessionManager\Security\LogInAuthenticationHandler'
---
Name: session-manager-log-out-handler
Before: '#coreauthentication'
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Security\AuthenticationHandler:
    properties:
      Handlers:
        LoginSessionLogOut: '%$SilverStripe\SessionManager\Security\LogOutAuthenticationHandler'
---
Name: session-manager-middleware
After: '#coresecurity'
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Control\Director:
    properties:
      Middlewares:
        LoginSessionMiddleware: '%$SilverStripe\SessionManager\Control\LoginSessionMiddleware'
